{"name": "test_create_auth_with_excel", "status": "broken", "statusDetails": {"message": "KeyError: 'token'", "trace": "def test_create_auth_with_excel():\n        #file_path = Path(__file__).parent / \"testdata_ddt.xlsx\"\n        file_path=\"C:/Users/mutay/OneDrive/Documents/courses/PyATB/code files/pyProject1-AutomationFramework/tests/test/datadriventesting/testdata_ddt.xlsx\"\n        credentials=read_credentials_from_excel(file_path)\n    \n        for user in credentials:\n            username=user[\"username\"]\n            password=user[\"password\"]\n    \n            response=create_auth_request(username=user[\"username\"],password=user[\"password\"])\n            assert response.status_code==200\n>           assert response.json()[\"token\"] is not None\nE           KeyError: 'token'\n\ntests\\test\\datadriventesting\\test_ddt_for.py:59: KeyError"}, "start": 1735556421469, "stop": 1735556422512, "uuid": "e39760ef-9540-4e66-a798-9d474e2512aa", "historyId": "2f5942487badef0e1dd87d799b3006c7", "testCaseId": "2f5942487badef0e1dd87d799b3006c7", "fullName": "tests.test.datadriventesting.test_ddt_for#test_create_auth_with_excel", "labels": [{"name": "parentSuite", "value": "tests.test.datadriventesting"}, {"name": "suite", "value": "test_ddt_for"}, {"name": "host", "value": "Dell15"}, {"name": "thread", "value": "35896-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test.datadriventesting.test_ddt_for"}]}